version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: hydrogen_elasticsearch
    volumes:
      - esdata1:/usr/share/elasticsearch/data /usr/share/elasticsearch/logs/docker-cluster.log
    environment:
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=trial
    ports:
      - "9200:9200"
    networks:
      - elasticnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  redis:
    image: redis
    container_name: hydrogen_redis
    ports:
      - "6379:6379"
    networks:
      - elasticnet
    volumes:
      - redisdata1:/data

volumes:
  esdata1:
    driver: local
  redisdata1:
    driver: local

networks:
  elasticnet:
    driver: bridge
